l_turkish:
 com_topbar_configuration_button_tooltip: "Üst Bar Yapılandırmasını Aç"
 com_topbar_configuration_title: "Üst Bar Yapılandırması"
 com_topbar_configuration_current: "Mevcut Üst Bar"
 com_topbar_configuration_add: "Üst Barı Düzenle"
 com_topbar_configuration_always_show: "Üst bar öğelerini her zaman göster (#r Pencerelerin üzerine biner#!)"
 com_topbar_configuration_add_explanation: "Aşağıdaki butonları kullanarak üst bara öğe ekleyin veya kaldırın."
 com_topbar_configuration_clear_first_tooltip: "Birinci üst bar satırını temizle."
 com_topbar_configuration_add_first_tooltip: "Bu öğeyi birinci üst bar satırına ekle."
 com_topbar_configuration_remove_first_tooltip: "Bu öğeyi birinci üst bar satırından kaldır."
 com_topbar_configuration_clear_second_tooltip: "İkinci üst bar satırını temizle."
 com_topbar_configuration_add_second_tooltip: "Bu öğeyi ikinci üst bar satırına ekle."
 com_topbar_configuration_remove_second_tooltip: "Bu öğeyi ikinci üst bar satırından kaldır."
 com_topbar_configuration_add_header_source: "Öğe Kaynağı"
 com_topbar_configuration_add_header_element: "Üst Bar Öğesi"
 com_topbar_configuration_add_header_first: "Birinci\nSatır"
 com_topbar_configuration_add_header_second: "İkinci\nSatır"
